# Site settings
title: FAUST'S CAT 
email: faustmeow@outlook.com
description: "FAUST'S CAT HOME"
baseurl: ""
url: "hongbiao.me"
username: 'faustmeow'
highlighter: pygments
repository: "https://github.com/chenhongbiao"
paginate: 10

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: :title

# chart_apis
chart_apis: http://chart.apis.google.com/chart?cht=tx&chl=